### ISSUE TITLE
several issues

### ISSUE THREAD

**Issue by BTNC** [xaizek/vim-inccomplete#5] opened 2016-11-09 12:05 UTC
Hi, 
Thanks for the useful vim plugin. I have the following issues:
1. subdirs do not work if path has white space
2. win32unix (for cygwin) should not be regarded as isWindows, cygwin is following unix path convention
3. [the regex in case of /](https://github.com/xaizek/vim-inccomplete/blob/master/plugin/inccomplete.vim#L112) should better not make the assumption that the end is not " or >, ie `'^\s*#\s*include\s*["<].*$'`

**Comment by xaizek** [comment] 2016-11-09 12:57
Hi,

1. This seems to be done by Vim rather than the plugin. Space is not in `'iskeyword'`, so when you press it Vim assumes that completion is over.
2. Thanks for this.
3. I think it was done intentionally because otherwise you are left with original path suffix which doesn't go anywhere after completion is done. Maybe you want to handle only paths what end with `/"` or  `/>`?

I added some changes in `issue-5` branch. There is a crude workaround for spaces (I'm not sure we should change `'iskeyword'`, remapping of space seems to work), but maybe it will work for you. And regexp is changed there, try adding `/` in the middle of the path (e.g. after `sys` in `<syssomthing>`) to see why it might be the way it's now.

**Comment by BTNC** [comment] 2016-11-09 13:52
1. I am walking around this issue by adding `  let l:pathlst = substitute(l:pathlst, " ", "\\\\ ", "g")` after [this line](https://github.com/xaizek/vim-inccomplete/blob/master/plugin/inccomplete.vim#L486)
3. The problem is if I have `g:inccomplete_addclosebracket == "always"`, if I type `<` after `#include`, a `>` will be appended. After I typed `dir/`, header completion will not happen since there is a trailing `>`. I am using `let g:inccomplete_addclosebracket = "no"` in .vimrc to walk around it. 
Another problem with `g:inccomplete_addclosebracket == "always"` is after I typed Backspace to remove the completion, the trailing `>` is still there.

**Comment by xaizek** [comment] 2016-11-09 15:54
`1`. Then that's a different issue, which I don't have on GNU/Linux. Applied your version. Thanks.

`3`. So handling only trailing case should address this. As for removal of closing symbol, added handling of backspace key.

Updated the branch. And the docs might need change of wording, it's not a strict requirement, just something that did work, probably just say that it should work with neocomplete.

**Comment by BTNC** [comment] 2016-11-10 13:18
I tried issue-5 branch, the white space in subdirs problem is gone. However, backspace is not working conveniently when `g:inccomplete_addclosebracket == "always"`. Backspace simply delete current character instead of the whole completion. Instead I am using `g:inccomplete_addclosebracket == "no"`, and I think this is enough (convenient enough without 'always').

**Comment by xaizek** [comment] 2016-11-10 13:27
> Backspace simply delete current character instead of the whole completion.

I though you entering <kbd>"</kbd>, getting `"|"` and then changing your mind and typing <kbd>&lt;bs&gt;</kbd><kbd>&lt;</kbd>. Removal of whole completion would be unexpected behaviour for a backspace, I usually use <kbd>&lt;c-w&gt;</kbd> or you can press <kbd>&lt;c-e&gt;</kbd> to undo insertion of current completion result.

> Instead I am using g:inccomplete_addclosebracket == "no", and I think this is enough (convenient enough without 'always').

Then I'll drop commit with mapping of backspace, it might cause conflicts for some configurations.

**Comment by BTNC** [comment] 2016-11-10 13:45
I think the backspace behavior is from neocomplete. For example, enter `<`, then tab to select a header like algorithm, `algorithm>` will be inserted into code, then backspace, the completion part `algorithm>` and last entered character `<` are deleted.
Thanks you!

**Closed** 2016-11-12 13:45 UTC
